### ISSUE TITLE
Do we use javascript or dart to program our API for the crawler?

### ISSUE THREAD

**Issue by lx1922** [GDSCUTM-CommunityProjects/ActNow#27]
**Feature purpose**
We already know that there is a good documented API on puppeteer in Javascript, however not sure if we wanna keep dart/flutter across the application

**Ideal solution**
Each of them have their pros and cons

https://pub.dev/packages/puppeteer/install

**Comment by TheFatPanda97** [comment]
let's use js, the reason being we would want to ideally use the puppeteer-cluter library which is only available on node.

**Comment by lx1922** [comment]
Okay cool! 👍

**Comment by TheFatPanda97** [comment]
@Goutam112 I saw that you used the dart version to scrape the code which is really awesome, but can you and Shrey convert to the js version, sorry In know it's some repeated work 🙏

**Comment by Goutam112** [comment]
Will work on recreating in JS tmrw. Shouldn't be too difficult
