### ISSUE TITLE
Improve scraper functionality (Add controller for scraper API)

### ISSUE THREAD

**Issue by Goutam112** [GDSCUTM-CommunityProjects/ActNow#75]
**Feature purpose**
Add a dynamic variable to the scraper which refers to the location to scrape events for from Eventbrite.

**Solution**
Create a controller file that passes in a string input referring to the city name (eg: "Toronto", "Mississauga", etc.) and calls the scraper file. The location is a dynamic variable in the scraper file that is passed in the webpageUrl variable
(eg: `https://www.eventbrite.ca/d/${location}/all-events/?page=1`)

**Comment by TheFatPanda97** [comment]
This is done here #86
